application:
  version: @project.version@
spring:
  datasource:
    url: ${DB_JDBC_URL:jdbc:h2:mem:testdb;Mode=PostgreSQL}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:''}
    platform: postgresql
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      max-lifetime: 45000
      connection-timeout: 30000
      idle-timeout: 35000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class:  org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  flyway:
    enabled: false
migrate:
  url: ${MIGRATION_URL:https://localhost}

